### ISSUE TITLE
reset text area size to normal value is not working after submitting text area value.

### ISSUE THREAD

**Issue by jayaramasaipavanmanda** [chrum/ngx-autosize#30]
Add lines in text area , submit the text using a button, the text area size doesn't seems to reset to intial value.If this functionality already exists, please let me know how to use it.

**Comment by chrum** [comment]
Hey,

I am scratching my head and trying to understand your issue as your problem is not completely clear for me...

If i correctly grasped the idea... please check the [demo page](https://chrum.it/pages/ngx-autosize/) and the example i just added in the bottom...

let me know if that is your situation :)

**Comment by jayaramasaipavanmanda** [comment]
Hi @chrum this is the thing I want. Could you please let me know how to use it?Thanks.

**Comment by chrum** [comment]
check this commit https://github.com/chrum/ngx-autosize/commit/e5631b2f4439d8682655db6f71b8efc995b21e3f
