### ISSUE TITLE
Latest update causes compilation error when autosize is not set a value

### ISSUE THREAD

**Issue by karptonite** [chrum/ngx-autosize#85]
the latest update allows the directive to be dynamically enabled, which is great:
```<textarea [autosize]="true"></textarea>```

However, I'm finding that for most uses with the old syntax,
```<textarea autosize></textarea>```
I'm getting a compilation error: ` Type 'string' is not assignable to type 'boolean'.`

**Comment by chrum** [comment]
i am on it :)

**Comment by chrum** [comment]
hmmmm i tried to reproduce this issue but no luck... anything special in your code? 

i tested
```<textarea autosize></textarea>```
both serving and building (with --prod flag with ng 5) and no errors

can you put together small stackblitz example?

**Comment by shestakovich** [comment]
I have the same problem. angular 12.2.14

**Comment by karptonite** [comment]
Sorry, I’m out of town this week. I’ll see what I can do when I get back.

**Comment by chrum** [comment]
hmmm my bad :( i checked old ng and latest... 12 is something i didnt check, sorry guys
just released 1.8.7 which should be fixing this issue

**Comment by keliel** [comment]
So this is where version 1.8.7 is coming from. I was wondering, since there is no specific tag in this repo 😅 
It sounds to me as if this is an issue with the strictInputAccessModifiers flag, now that the directives immediate input is defined as being boolean rather than string. Will double check in my ng13 setup with the flag being enabled @chrum
